# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dragontek.company::lang.testimonial.label

# Model Form Field configuration
form: $/dragontek/company/models/testimonial/fields.yaml

# Model Class name
modelClass: Dragontek\Company\Models\Testimonial

# Default redirect location
defaultRedirect: dragontek/company/testimonials

# Create page
create:
    title: dragontek.company::lang.testimonial.create_title
    redirect: dragontek/company/testimonials/update/:id
    redirectClose: dragontek/company/testimonials

# Update page
update:
    title: dragontek.company::lang.testimonial.update_title
    redirect: dragontek/company/testimonials
    redirectClose: dragontek/company/testimonials

# Preview page
preview:
    title: dragontek.company::lang.testimonial.preview_title