# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dragontek.company::lang.employee.label

# Model Form Field configuration
form: $/dragontek/company/models/employee/fields.yaml

# Model Class name
modelClass: Dragontek\Company\Models\Employee

# Default redirect location
defaultRedirect: dragontek/company/employees

# Create page
create:
    title: dragontek.company::lang.employee.create_title
    redirect: dragontek/company/employees/update/:id
    redirectClose: dragontek/company/employees

# Update page
update:
    title: dragontek.company::lang.employee.update_title
    redirect: dragontek/company/employees
    redirectClose: dragontek/company/employees

# Preview page
preview:
    title: dragontek.company::lang.employee.preview_title