# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dragontek.company::lang.service.label

# Model Form Field configuration
form: $/dragontek/company/models/service/fields.yaml

# Model Class name
modelClass: Dragontek\Company\Models\Service

# Default redirect location
defaultRedirect: dragontek/company/services

# Create page
create:
    title: dragontek.company::lang.service.create_title
    redirect: dragontek/company/services/update/:id
    redirectClose: dragontek/company/services

# Update page
update:
    title: dragontek.company::lang.service.update_title
    redirect: dragontek/company/services
    redirectClose: dragontek/company/services

# Preview page
preview:
    title: dragontek.company::lang.service.preview_title