# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dragontek.company::lang.gallery.label

# Model Form Field configuration
form: $/dragontek/company/models/gallery/fields.yaml

# Model Class name
modelClass: Dragontek\Company\Models\Gallery

# Default redirect location
defaultRedirect: dragontek/company/galleries

# Create page
create:
    title: dragontek.company::lang.gallery.create_title
    redirect: dragontek/company/galleries/update/:id
    redirectClose: dragontek/company/galleries

# Update page
update:
    title: dragontek.company::lang.gallery.update_title
    redirect: dragontek/company/galleries
    redirectClose: dragontek/company/galleries

# Preview page
preview:
    title: dragontek.company::lang.gallery.preview_title