# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dragontek.company::lang.tag.label

# Model Form Field configuration
form: $/dragontek/company/models/tag/fields.yaml

# Model Class name
modelClass: Dragontek\Company\Models\Tag

# Default redirect location
defaultRedirect: dragontek/company/tags

# Create page
create:
    title: dragontek.company::lang.tag.create_title
    redirect: dragontek/company/tags/update/:id
    redirectClose: dragontek/company/tags

# Update page
update:
    title: dragontek.company::lang.tag.update_title
    redirect: dragontek/company/tags
    redirectClose: dragontek/company/tags

# Preview page
preview:
    title: dragontek.company::lang.tag.preview_title