# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dragontek.company::lang.project.label

# Model Form Field configuration
form: $/dragontek/company/models/project/fields.yaml

# Model Class name
modelClass: Dragontek\Company\Models\Project

# Default redirect location
defaultRedirect: dragontek/company/projects

# Create page
create:
    title: dragontek.company::lang.project.create_title
    redirect: dragontek/company/projects/update/:id
    redirectClose: dragontek/company/projects

# Update page
update:
    title: dragontek.company::lang.project.update_title
    redirect: dragontek/company/projects
    redirectClose: dragontek/company/projects

# Preview page
preview:
    title: dragontek.company::lang.project.preview_title