# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: dragontek.company::lang.link.label

# Model Form Field configuration
form: $/dragontek/company/models/link/fields.yaml

# Model Class name
modelClass: Dragontek\Company\Models\Link

# Default redirect location
defaultRedirect: dragontek/company/links

# Create page
create:
    title: dragontek.company::lang.link.create_title
    redirect: dragontek/company/links/update/:id
    redirectClose: dragontek/company/links

# Update page
update:
    title: dragontek.company::lang.link.update_title
    redirect: dragontek/company/links
    redirectClose: dragontek/company/links

# Preview page
preview:
    title: dragontek.company::lang.link.preview_title